version: '3'
services:
   postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/socks'
      - 'SPRING_DATASOURCE_PASSWORD=11111111'
      - 'SPRING_DATASOURCE_USERNAME=igr'
      - 'POSTGRES_DB=socks'
    ports:
      - '5432:5432'


   app:
     build: ./
     container_name: 'sock'
     ports:
       - '8081:8081'






